#!/bin/sh
# Test shell script that demonstrates looping by searching through the PATH and listing executables.

myname=`basename $0`

for dir in `echo "$PATH" | tr ':' ' '`
do
    cd $dir

    for file in *
    do
        if [ -x "$file" -a ! -d "$file" ]
        then
            echo "$file"
        fi
    done
done | sort | grep "$1" | column 
